# Generated by Django 4.2.7 on 2023-11-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=20)),
                ('name', models.TextField(blank=True, max_length=100)),
                ('age', models.IntegerField(blank=True, max_length=100)),
                ('standard', models.IntegerField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
